---
driver:
  name: vagrant

provisioner:
  require_chef_omnibus: true

platforms:
- name: ubuntu-10.04
  run_list: ["recipe[apt]"]
- name: ubuntu-12.04
  run_list: ["recipe[apt]"]
- name: ubuntu-14.04
  run_list: ["recipe[apt]"]
- name: debian-6.0.10
  run_list: ["recipe[apt]"]
- name: debian-7.6
  run_list: ["recipe[apt]"]
- name: centos-5.10
- name: centos-6.5
- name: centos-7.0
- name: fedora-18
- name: fedora-19
- name: fedora-20

suites:
- name: default
  run_list:
  - recipe[dovecot_test]
- name: attributes
  run_list:
  - recipe[dovecot_test::attributes]
